import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Provider from "@/app/components/Provider";
import NavigationMenu from "@/app/components/navigationMenu/NavigationMenu";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} dark:bg-deep-purple bg-ghost-white dark:text-ghost-white text-deep-purple min-h-screen`}
      >
        <Provider>
          <div
            className={
              "absolute top-[20%] left-[20%] w-[400px] h-[400px] max-w-[75%] max-h-[75%] bg-purple rounded-full blur-[95px] opacity-30 -z-10"
            }
          ></div>
          <header className="max-w-screen-lg m-auto pt-10 px-4 lg:px-0">
            <NavigationMenu />
          </header>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
