import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Provider from "@/app/components/Provider";
import HomepageHero from "@/app/components/HomepageHero";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} dark:bg-[#6D6F85] dark:text-white`}>
        <Provider>
        <HomepageHero />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
