import '../globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import Provider from '@/app/components/Provider';
import NavigationMenu from '@/app/components/navigationMenu/NavigationMenu';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} dark:bg-deep-purple bg-white dark:text-ghost-white text-deep-purple min-h-screen`}
      >
        <Provider>
          <div
            className={
              'absolute top-[90%] left-[50%] -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] max-w-[75%] max-h-[75%] bg-purple rounded-full blur-[85px] opacity-30 -z-10'
            }
          ></div>
          <header>
            <NavigationMenu />
          </header>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
